"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.autosRoutes = void 0;
const express_1 = require("express");
const autos_controller_1 = require("../controllers/autos_controller");
exports.autosRoutes = (0, express_1.Router)();
exports.autosRoutes.get('/getautos', autos_controller_1.getAutos);
exports.autosRoutes.get('/getautosbyid/:id', autos_controller_1.getAutosById);
exports.autosRoutes.post('/createautos', autos_controller_1.createAutos);
exports.autosRoutes.delete('/deleteautos/:id', autos_controller_1.deleteAuto);
exports.autosRoutes.put('/updateauto/:id', autos_controller_1.updateAutos);
